# Generated by Django 5.2 on 2025-05-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='drug_side_effect_prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=300)),
                ('Drug_Name', models.CharField(max_length=3000)),
                ('Condition1', models.CharField(max_length=3000)),
                ('Prediction', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
