# Generated by Django 5.2 on 2025-05-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0008_detection_accuracy_detection_ratio_and_more'),
    ]

    operations = [
    ]
